### Import

In [1]:
import pandas as pd 
import numpy as np

In [2]:
#fonctions utiles pour présidentielles 

Base = ['Code du département', 'Libellé du département',
       'Code de la circonscription', 'Libellé de la circonscription',
       'Code de la commune', 'Libellé de la commune', 'Code du b.vote',
       'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins',
       'Blancs', '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins',
       '% Nuls/Vot', 'Exprimés', '% Exp/Ins', '% Exp/Vot']
Candidat = [ 'N°Panneau', 'Sexe',
       'Nom', 'Prénom', 'Voix', '% Voix/Ins', '% Voix/Exp']

#function to fill the columns index,

def fill_columns_index (shape) : 
    columns = Base.copy() 
    i = 0
    while len(columns) < shape : 
        #adding the candidat columns plus identifier 
        i += 1
        columns.extend([ ele + str(i) for ele in Candidat])
    return columns



#extracting Base data, and candidates data one candidate by one candidate  and merge it iteratively to a single dataframe
def extract_data(df, shape) :
    columns = fill_columns_index(shape)
    df.columns = columns
    df_base = df[Base]
  #iterating over 7 columns of candidates data starting from 19th column
    for i in range(21, shape, 7):
        df_candidat = df[columns[i:i+7]]
        df_candidat.columns = Candidat
        df_candidat = df_candidat.fillna(method='ffill')
        df_candidat = df_candidat.fillna(method='bfill')
        df_candidat = df_candidat.fillna(0)
        df_candidat = df_candidat.reset_index(drop=True)
        df_candidat = df_candidat.drop(['N°Panneau'], axis=1)
        df_candidat = df_candidat.drop(['Sexe'], axis=1)
        if i == 21:
            df_new= pd.concat([df_base, df_candidat], axis=1)
        else:
            df_new = pd.concat([df_new, pd.concat([df_base, df_candidat], axis=1)], axis=0)
    
    return df_new

## <center> **`Présidentielles`**

## `Présidentielles : 2022`

### **Tour 1**

In [3]:
file='data/resultats-par-niveau-burvot-t1-france-entiere.xlsx'
df=pd.read_excel(file)

In [4]:
df.columns[:30]

Index(['Code du département', 'Libellé du département',
       'Code de la circonscription', 'Libellé de la circonscription',
       'Code de la commune', 'Libellé de la commune', 'Code du b.vote',
       'Inscrits', 'Abstentions', '% Abs/Ins', 'Votants', '% Vot/Ins',
       'Blancs', '% Blancs/Ins', '% Blancs/Vot', 'Nuls', '% Nuls/Ins',
       '% Nuls/Vot', 'Exprimés', '% Exp/Ins', '% Exp/Vot', 'N°Panneau', 'Sexe',
       'Nom', 'Prénom', 'Voix', '% Voix/Ins', '% Voix/Exp', 'Unnamed: 28',
       'Unnamed: 29'],
      dtype='object')

In [5]:
raw_2022_T1 = extract_data(df, df.shape[1])
raw_2022_T1["Election"] = "Presidentielle 2022"
raw_2022_T1["Tour"]= 1

### **Tour 2**

In [6]:
file = 'data/resultats-par-niveau-burvot-t2-france-entiere.csv'
df = pd.read_csv(file, sep=';',encoding='latin-1', header = None, skiprows=1)
raw_2022_T2 = extract_data(df, df.shape[1])

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1718399321.py:2: DtypeWarning: Columns (0,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=';',encoding='latin-1', header = None, skiprows=1)

In [7]:
raw_2022_T2

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,% Nuls/Ins,% Nuls/Vot,Exprimés,% Exp/Ins,% Exp/Vot,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp
0,01,Ain,4,4ème circonscription,1,L'Abergement-Clémenciat,0001,643,146,"22,71",...,"0,78","1,01",450,"69,98","90,54",MACRON,Emmanuel,237,"36,86","52,67"
1,01,Ain,5,5ème circonscription,2,L'Abergement-de-Varey,0001,213,45,"21,13",...,"1,41","1,79",142,"66,67","84,52",MACRON,Emmanuel,94,"44,13","66,20"
2,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0001,1130,322,"28,50",...,"1,95","2,72",715,"63,27","88,49",MACRON,Emmanuel,360,"31,86","50,35"
3,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0002,1129,313,"27,72",...,"1,59","2,21",753,"66,70","92,28",MACRON,Emmanuel,426,"37,73","56,57"
4,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0003,1213,303,"24,98",...,"1,73","2,31",802,"66,12","88,13",MACRON,Emmanuel,449,"37,02","55,99"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69677,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,24867,13153,"52,89",...,"0,20","0,42",11438,"46,00","97,64",LE PEN,Marine,1272,"5,12","11,12"
69678,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipei,1,1703,928,"54,49",...,"0,35","0,77",743,"43,63","95,87",LE PEN,Marine,132,"7,75","17,77"
69679,ZZ,Français établis hors de France,11,11ème circonscription,233,Nour-Soultan,1,117,64,"54,70",...,"0,00","0,00",50,"42,74","94,34",LE PEN,Marine,11,"9,40","22,00"
69680,ZZ,Français établis hors de France,2,2ème circonscription,234,Monterrey,1,715,510,"71,33",...,"0,14","0,49",202,"28,25","98,54",LE PEN,Marine,21,"2,94","10,40"
69681,ZZ,Français établis hors de France,2,2ème circonscription,235,Bahamas (Nassau),1,137,78,"56,93",...,"0,73","1,69",51,"37,23","86,44",LE PEN,Marine,16,"11,68","31,37"

In [8]:
raw_2022_T2["Election"] = "Presidentielle 2022"
raw_2022_T2["Tour"]= 2

## `Présidentielles :2017`

### **Tour 1**

In [9]:
file = "data/PR17_BVot_T1_FE.csv"

df = pd.read_csv(file, sep=";", encoding="latin-1",header=None, skiprows=1)
print("the shape of the dataframe is: ", df.shape)

the shape of the dataframe is:  (69242, 98)

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1839127520.py:3: DtypeWarning: Columns (0,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1",header=None, skiprows=1)

In [10]:
df

,0,1,2,3,4,5,6,7,8,9,...,88,89,90,91,92,93,94,95,96,97
0,1,Ain,4,4ème circonscription,1,L'Abergement-Clémenciat,1.0,598,92,"15,38",...,6,1,"1,21",11,M,FILLON,François,110,"18,39","22,22"
1,1,Ain,5,5ème circonscription,2,L'Abergement-de-Varey,1.0,209,25,"11,96",...,1,"0,48","0,57",11,M,FILLON,François,34,"16,27","19,32"
2,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,1.0,1116,233,"20,88",...,7,"0,63","0,81",11,M,FILLON,François,116,"10,39","13,49"
3,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,2.0,1128,256,"22,7",...,11,"0,98","1,29",11,M,FILLON,François,124,"10,99","14,59"
4,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,3.0,1116,227,"20,34",...,7,"0,63","0,8",11,M,FILLON,François,149,"13,35","17,05"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69237,ZZ,Français établis hors de France,11,11ème circonscription,226,Wuhan,1,369,129,"34,96",...,3,"0,81","1,27",11,M,FILLON,François,62,"16,8","26,27"
69238,ZZ,Français établis hors de France,10,10ème circonscription,227,Yaounde,1,1514,800,"52,84",...,4,"0,26","0,56",11,M,FILLON,François,197,"13,01","27,71"
69239,ZZ,Français établis hors de France,7,7ème circonscription,228,Zagreb,1,655,401,"61,22",...,6,"0,92","2,39",11,M,FILLON,François,65,"9,92","25,9"
69240,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,21477,11129,"51,82",...,87,"0,41","0,85",11,M,FILLON,François,2893,"13,47","28,24"
69241,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipeh,1,1204,519,"43,11",...,35,"2,91","5,18",11,M,FILLON,François,113,"9,39","16,72"

In [11]:
raw_T1_2017 = extract_data(df, df.shape[1])
raw_T1_2017["Election"] = "Presidentielle 2017"
raw_T1_2017["Tour"]= 1

### **Tour 2**

In [12]:
file = "data/PR17_BVot_T2_FE.csv"

df = pd.read_csv(file, sep=";", encoding="latin-1",header=None, skiprows=1)
print("the shape of the dataframe is: ", df.shape)

the shape of the dataframe is:  (69242, 35)

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1496989987.py:3: DtypeWarning: Columns (0,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1",header=None, skiprows=1)

In [13]:
raw_T2_2017 = extract_data(df, df.shape[1])
raw_T2_2017["Election"] = "Presidentielle 2017"
raw_T2_2017["Tour"]= 2

In [14]:
raw_T2_2017

,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,Exprimés,% Exp/Ins,% Exp/Vot,Nom,Prénom,Voix,% Voix/Ins,% Voix/Exp,Election,Tour
0,01,Ain,4,4ème circonscription,1,L'Abergement-Clémenciat,0001,598,100,"16,72",...,453,"75,75","90,96",MACRON,Emmanuel,272,"45,48","60,04",Presidentielle 2017,2
1,01,Ain,5,5ème circonscription,2,L'Abergement-de-Varey,0001,209,32,"15,31",...,150,"71,77","84,75",MACRON,Emmanuel,93,"44,50","62,00",Presidentielle 2017,2
2,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0001,1116,267,"23,92",...,731,"65,50","86,10",MACRON,Emmanuel,416,"37,28","56,91",Presidentielle 2017,2
3,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0002,1128,286,"25,35",...,741,"65,69","88,00",MACRON,Emmanuel,429,"38,03","57,89",Presidentielle 2017,2
4,01,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,0003,1116,252,"22,58",...,753,"67,47","87,15",MACRON,Emmanuel,453,"40,59","60,16",Presidentielle 2017,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69237,ZZ,Français établis hors de France,11,11ème circonscription,226,Wuhan,1,369,155,"42,01",...,204,"55,28","95,33",LE PEN,Marine,19,"5,15","9,31",Presidentielle 2017,2
69238,ZZ,Français établis hors de France,10,10ème circonscription,227,Yaounde,1,1517,788,"51,94",...,690,"45,48","94,65",LE PEN,Marine,109,"7,19","15,80",Presidentielle 2017,2
69239,ZZ,Français établis hors de France,7,7ème circonscription,228,Zagreb,1,656,411,"62,65",...,235,"35,82","95,92",LE PEN,Marine,53,"8,08","22,55",Presidentielle 2017,2
69240,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,21488,10241,"47,66",...,10888,"50,67","96,81",LE PEN,Marine,1112,"5,17","10,21",Presidentielle 2017,2
69241,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipeh,1,1212,573,"47,28",...,619,"51,07","96,87",LE PEN,Marine,87,"7,18","14,05",Presidentielle 2017,2

## ` Présidentielles : 2012`

### **Tour 1 & 2**

In [15]:
file='data/PR12_Bvot_T1T2.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1")

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/2756794556.py:2: DtypeWarning: Columns (1,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1")

In [16]:
df

,1,ZA,101,Les Abymes,01,01.1,0001,476,266,249,2,JOLY,Eva,JOLY.1,7
0,1,ZA,101,Les Abymes,1,1,1,476,266,249,3,LE PEN,Marine,LEPE,12
1,1,ZA,101,Les Abymes,1,1,1,476,266,249,4,SARKOZY,Nicolas,SARK,50
2,1,ZA,101,Les Abymes,1,1,1,476,266,249,5,MÉLENCHON,Jean-Luc,MELE,11
3,1,ZA,101,Les Abymes,1,1,1,476,266,249,9,BAYROU,François,BAYR,5
4,1,ZA,101,Les Abymes,1,1,1,476,266,249,11,HOLLANDE,François,HOLL,160
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
815178,2,95,680,Villiers-le-Bel,8,35,13,655,490,469,11,HOLLANDE,François,HOLL,392
815179,2,95,682,Villiers-le-Sec,9,15,1,95,87,83,4,SARKOZY,Nicolas,SARK,42
815180,2,95,682,Villiers-le-Sec,9,15,1,95,87,83,11,HOLLANDE,François,HOLL,41
815181,2,95,690,Wy-dit-Joli-Village,1,16,1,279,249,240,4,SARKOZY,Nicolas,SARK,150
815182,2,95,690,Wy-dit-Joli-Village,1,16,1,279,249,240,11,HOLLANDE,François,HOLL,90

In [17]:
Colonnes = ['Tour',
'Code du département',
'Code de la commune',
'Libellé de la commune',
'Code de la circonscription',
'Code du canton',
'Code du b.vote',
'Inscrits',
'Votants',
'Exprimés',
'N°Panneau',
'Nom',
'Prénom',
'Nuance',
'Voix']

In [18]:
df.columns = Colonnes

In [19]:
raw_2012_T1T2 = df
raw_2012_T1T2["Election"] = "Presidentielle 2012"

## `Présidentielles : 2007`

### **Tour 1 & 2**

In [20]:
file='data/PR07_Bvot_T1T2.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1",skiprows=17,header=None)

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/3303136723.py:2: DtypeWarning: Columns (1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1",skiprows=17,header=None)

In [21]:
df

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,5,BOVÉ,José,BOVE,5
1,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,2,BUFFET,Marie-George,BUFF,3
2,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,3,SCHIVARDI,Gérard,SCHI,1
3,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,11,LAGUILLER,Arlette,LAGU,6
4,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,7,de VILLIERS,Philippe,VILL,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
918633,2,ZM,517,TSINGONI,73,694,296,293,12,SARKOZY,Nicolas,SARK,143
918634,2,ZM,517,TSINGONI,74,635,236,231,8,ROYAL,Ségolène,ROYA,142
918635,2,ZM,517,TSINGONI,74,635,236,231,12,SARKOZY,Nicolas,SARK,89
918636,2,ZM,517,TSINGONI,99,175,89,88,8,ROYAL,Ségolène,ROYA,55
918637,2,ZM,517,TSINGONI,99,175,89,88,12,SARKOZY,Nicolas,SARK,33

In [22]:
Colonnes = ['Tour',
'Code du département',
'Code de la commune',
'Libellé de la commune',
'Code du b.vote',
'Inscrits',
'Votants',
'Exprimés',
'N°Panneau',
'Nom',
'Prénom',
'Nuance',
'Voix']

df.columns = Colonnes

In [23]:
raw_2007_T1T2 = df

In [24]:
raw_2007_T1T2

,Tour,Code du département,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Votants,Exprimés,N°Panneau,Nom,Prénom,Nuance,Voix
0,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,5,BOVÉ,José,BOVE,5
1,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,2,BUFFET,Marie-George,BUFF,3
2,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,3,SCHIVARDI,Gérard,SCHI,1
3,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,11,LAGUILLER,Arlette,LAGU,6
4,1,1,1,L'Abergement-Clémenciat,0001,596,528,522,7,de VILLIERS,Philippe,VILL,20
...,...,...,...,...,...,...,...,...,...,...,...,...,...
918633,2,ZM,517,TSINGONI,73,694,296,293,12,SARKOZY,Nicolas,SARK,143
918634,2,ZM,517,TSINGONI,74,635,236,231,8,ROYAL,Ségolène,ROYA,142
918635,2,ZM,517,TSINGONI,74,635,236,231,12,SARKOZY,Nicolas,SARK,89
918636,2,ZM,517,TSINGONI,99,175,89,88,8,ROYAL,Ségolène,ROYA,55
918637,2,ZM,517,TSINGONI,99,175,89,88,12,SARKOZY,Nicolas,SARK,33

In [25]:
raw_2012_T1T2["Election"] = "Presidentielle 2007"

## <center> **`Législatives`**

## **`Législatives : 2022`**

### **Tour 1**

In [26]:
file='data/T1_bueau_leg_2022.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(197)))

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1982446982.py:2: DtypeWarning: Columns (0,2,4,6,7,8,10,12,15,18,21,26,126,127,128,129,131,132,134,135,136,137,139,140,142,143,144,145,147,148,150,151,152,153,155,156,158,159,160,161,163,164,166,167,168,169,171,172,174,175,176,177,179,180,182,183,184,185,187,188,190,191,192,193,195,196) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(197)))

In [27]:
df

,0,1,2,3,4,5,6,7,8,9,...,187,188,189,190,191,192,193,194,195,196
0,Code du département,Libellé du département,Code de la circonscription,Libellé de la circonscription,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Abstentions,% Abs/Ins,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,01,Ain,04,4ème circonscription,001,L'Abergement-Clémenciat,0001,644,301,"46,74",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,01,Ain,05,5ème circonscription,002,L'Abergement-de-Varey,0001,218,85,"38,99",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,01,Ain,05,5ème circonscription,004,Ambérieu-en-Bugey,0001,1134,664,"58,55",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,01,Ain,05,5ème circonscription,004,Ambérieu-en-Bugey,0002,1141,625,"54,78",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69678,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,25067,18168,"72,48",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69679,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipei,1,1732,1238,"71,48",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69680,ZZ,Français établis hors de France,11,11ème circonscription,233,Nour-Soultan,1,115,77,"66,96",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69681,ZZ,Français établis hors de France,2,2ème circonscription,234,Monterrey,1,718,596,"83,01",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69682,ZZ,Français établis hors de France,2,2ème circonscription,235,Bahamas (Nassau),1,140,117,"83,57",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df.loc[0,:].to_list()[:32]

['Code du département',
 'Libellé du département',
 'Code de la circonscription',
 'Libellé de la circonscription',
 'Code de la commune',
 'Libellé de la commune',
 'Code du b.vote',
 'Inscrits',
 'Abstentions',
 '% Abs/Ins',
 'Votants',
 '% Vot/Ins',
 'Blancs',
 '% Blancs/Ins',
 '% Blancs/Vot',
 'Nuls',
 '% Nuls/Ins',
 '% Nuls/Vot',
 'Exprimés',
 '% Exp/Ins',
 '% Exp/Vot',
 'N°Panneau',
 'Sexe',
 'Nom',
 'Prénom',
 'Nuance',
 'Voix',
 '% Voix/Ins',
 '% Voix/Exp',
 nan,
 nan,
 nan]

In [29]:
Base = ['Code du département',
        'Libellé du département',
        'Code de la circonscription',
        'Libellé de la circonscription',
        'Code de la commune',
        'Libellé de la commune',
        'Code du b.vote',
        'Inscrits',
        'Abstentions',
        '% Abs/Ins',
        'Votants',
        '% Vot/Ins',
        'Blancs',
        '% Blancs/Ins',
        '% Blancs/Vot',
        'Nuls',
        '% Nuls/Ins',
        '% Nuls/Vot',
        'Exprimés',
        '% Exp/Ins',
        '% Exp/Vot']


Candidat = ['N°Panneau',
            'Sexe',
            'Nom',
            'Prénom',
            'Nuance',
            'Voix',
            '% Voix/Ins',
            '% Voix/Exp']



def fill_columns_index (shape) : 
    columns = Base.copy() 
    i = 0
    while len(columns) < shape : 
        #adding the candidat columns plus identifier 
        i += 1
        columns.extend([ ele + str(i) for ele in Candidat])
    return columns

 #extracting Base data, and candidates data one candidate by one candidate  and merge it iteratively to a single dataframe
def extract_data(df, shape) :
    columns = fill_columns_index(shape)
    df.columns = columns ##change it because of the shape of the dataframe manually set to 200
    df_base = df[Base]
  #iterating over 7 columns of candidates data starting from 19th column
    for i in range(21, shape, 8):
        print(columns[i:i+8])
        df_candidat = df[columns[i:i+8]]
        df_candidat.columns = Candidat
        df_candidat = df_candidat.fillna(method='ffill')
        df_candidat = df_candidat.fillna(method='bfill')
        df_candidat = df_candidat.fillna(0)
        df_candidat = df_candidat.reset_index(drop=True)
        df_candidat = df_candidat.drop(['N°Panneau'], axis=1)
        df_candidat = df_candidat.drop(['Sexe'], axis=1)
        if i == 21:
            df_new= pd.concat([df_base, df_candidat], axis=1)
        else:
            df_new = pd.concat([df_new, pd.concat([df_base, df_candidat], axis=1)], axis=0)
    
    return df_new

In [30]:
df = df.drop([0], axis=0)

In [31]:
df=extract_data(df, df.shape[1])

['N°Panneau1', 'Sexe1', 'Nom1', 'Prénom1', 'Nuance1', 'Voix1', '% Voix/Ins1', '% Voix/Exp1']
['N°Panneau2', 'Sexe2', 'Nom2', 'Prénom2', 'Nuance2', 'Voix2', '% Voix/Ins2', '% Voix/Exp2']
['N°Panneau3', 'Sexe3', 'Nom3', 'Prénom3', 'Nuance3', 'Voix3', '% Voix/Ins3', '% Voix/Exp3']
['N°Panneau4', 'Sexe4', 'Nom4', 'Prénom4', 'Nuance4', 'Voix4', '% Voix/Ins4', '% Voix/Exp4']
['N°Panneau5', 'Sexe5', 'Nom5', 'Prénom5', 'Nuance5', 'Voix5', '% Voix/Ins5', '% Voix/Exp5']
['N°Panneau6', 'Sexe6', 'Nom6', 'Prénom6', 'Nuance6', 'Voix6', '% Voix/Ins6', '% Voix/Exp6']
['N°Panneau7', 'Sexe7', 'Nom7', 'Prénom7', 'Nuance7', 'Voix7', '% Voix/Ins7', '% Voix/Exp7']
['N°Panneau8', 'Sexe8', 'Nom8', 'Prénom8', 'Nuance8', 'Voix8', '% Voix/Ins8', '% Voix/Exp8']
['N°Panneau9', 'Sexe9', 'Nom9', 'Prénom9', 'Nuance9', 'Voix9', '% Voix/Ins9', '% Voix/Exp9']
['N°Panneau10', 'Sexe10', 'Nom10', 'Prénom10', 'Nuance10', 'Voix10', '% Voix/Ins10', '% Voix/Exp10']
['N°Panneau11', 'Sexe11', 'Nom11', 'Prénom11', 'Nuance11', 'Voix11', '% Voix/Ins11', '% Voix/Exp11']
['N°Panneau12', 'Sexe12', 'Nom12', 'Prénom12', 'Nuance12', 'Voix12', '% Voix/Ins12', '% Voix/Exp12']
['N°Panneau13', 'Sexe13', 'Nom13', 'Prénom13', 'Nuance13', 'Voix13', '% Voix/Ins13', '% Voix/Exp13']
['N°Panneau14', 'Sexe14', 'Nom14', 'Prénom14', 'Nuance14', 'Voix14', '% Voix/Ins14', '% Voix/Exp14']
['N°Panneau15', 'Sexe15', 'Nom15', 'Prénom15', 'Nuance15', 'Voix15', '% Voix/Ins15', '% Voix/Exp15']
['N°Panneau16', 'Sexe16', 'Nom16', 'Prénom16', 'Nuance16', 'Voix16', '% Voix/Ins16', '% Voix/Exp16']
['N°Panneau17', 'Sexe17', 'Nom17', 'Prénom17', 'Nuance17', 'Voix17', '% Voix/Ins17', '% Voix/Exp17']
['N°Panneau18', 'Sexe18', 'Nom18', 'Prénom18', 'Nuance18', 'Voix18', '% Voix/Ins18', '% Voix/Exp18']
['N°Panneau19', 'Sexe19', 'Nom19', 'Prénom19', 'Nuance19', 'Voix19', '% Voix/Ins19', '% Voix/Exp19']
['N°Panneau20', 'Sexe20', 'Nom20', 'Prénom20', 'Nuance20', 'Voix20', '% Voix/Ins20', '% Voix/Exp20']
['N°Panneau21', 'Sexe21', 'Nom21', 'Prénom21', 'Nuance21', 'Voix21', '% Voix/Ins21', '% Voix/Exp21']
['N°Panneau22', 'Sexe22', 'Nom22', 'Prénom22', 'Nuance22', 'Voix22', '% Voix/Ins22', '% Voix/Exp22']

In [32]:
raw_2022_leg_T1 = df
raw_2022_leg_T1["Election"] = "Legislatives 2022"
raw_2022_leg_T1["Tour"] = 1

### **Tour 2**

In [33]:
file='data/T1_bueau_leg_2022.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(197)))
df = df.drop([0], axis=0)
df=extract_data(df, df.shape[1])
raw_2022_leg_T2 = df

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1575366550.py:2: DtypeWarning: Columns (0,2,4,6,7,8,10,12,15,18,21,26,126,127,128,129,131,132,134,135,136,137,139,140,142,143,144,145,147,148,150,151,152,153,155,156,158,159,160,161,163,164,166,167,168,169,171,172,174,175,176,177,179,180,182,183,184,185,187,188,190,191,192,193,195,196) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(197)))

['N°Panneau1', 'Sexe1', 'Nom1', 'Prénom1', 'Nuance1', 'Voix1', '% Voix/Ins1', '% Voix/Exp1']
['N°Panneau2', 'Sexe2', 'Nom2', 'Prénom2', 'Nuance2', 'Voix2', '% Voix/Ins2', '% Voix/Exp2']
['N°Panneau3', 'Sexe3', 'Nom3', 'Prénom3', 'Nuance3', 'Voix3', '% Voix/Ins3', '% Voix/Exp3']
['N°Panneau4', 'Sexe4', 'Nom4', 'Prénom4', 'Nuance4', 'Voix4', '% Voix/Ins4', '% Voix/Exp4']
['N°Panneau5', 'Sexe5', 'Nom5', 'Prénom5', 'Nuance5', 'Voix5', '% Voix/Ins5', '% Voix/Exp5']
['N°Panneau6', 'Sexe6', 'Nom6', 'Prénom6', 'Nuance6', 'Voix6', '% Voix/Ins6', '% Voix/Exp6']
['N°Panneau7', 'Sexe7', 'Nom7', 'Prénom7', 'Nuance7', 'Voix7', '% Voix/Ins7', '% Voix/Exp7']
['N°Panneau8', 'Sexe8', 'Nom8', 'Prénom8', 'Nuance8', 'Voix8', '% Voix/Ins8', '% Voix/Exp8']
['N°Panneau9', 'Sexe9', 'Nom9', 'Prénom9', 'Nuance9', 'Voix9', '% Voix/Ins9', '% Voix/Exp9']
['N°Panneau10', 'Sexe10', 'Nom10', 'Prénom10', 'Nuance10', 'Voix10', '% Voix/Ins10', '% Voix/Exp10']
['N°Panneau11', 'Sexe11', 'Nom11', 'Prénom11', 'Nuance11', 'Voix11', '% Voix/Ins11', '% Voix/Exp11']
['N°Panneau12', 'Sexe12', 'Nom12', 'Prénom12', 'Nuance12', 'Voix12', '% Voix/Ins12', '% Voix/Exp12']
['N°Panneau13', 'Sexe13', 'Nom13', 'Prénom13', 'Nuance13', 'Voix13', '% Voix/Ins13', '% Voix/Exp13']
['N°Panneau14', 'Sexe14', 'Nom14', 'Prénom14', 'Nuance14', 'Voix14', '% Voix/Ins14', '% Voix/Exp14']
['N°Panneau15', 'Sexe15', 'Nom15', 'Prénom15', 'Nuance15', 'Voix15', '% Voix/Ins15', '% Voix/Exp15']
['N°Panneau16', 'Sexe16', 'Nom16', 'Prénom16', 'Nuance16', 'Voix16', '% Voix/Ins16', '% Voix/Exp16']
['N°Panneau17', 'Sexe17', 'Nom17', 'Prénom17', 'Nuance17', 'Voix17', '% Voix/Ins17', '% Voix/Exp17']
['N°Panneau18', 'Sexe18', 'Nom18', 'Prénom18', 'Nuance18', 'Voix18', '% Voix/Ins18', '% Voix/Exp18']
['N°Panneau19', 'Sexe19', 'Nom19', 'Prénom19', 'Nuance19', 'Voix19', '% Voix/Ins19', '% Voix/Exp19']
['N°Panneau20', 'Sexe20', 'Nom20', 'Prénom20', 'Nuance20', 'Voix20', '% Voix/Ins20', '% Voix/Exp20']
['N°Panneau21', 'Sexe21', 'Nom21', 'Prénom21', 'Nuance21', 'Voix21', '% Voix/Ins21', '% Voix/Exp21']
['N°Panneau22', 'Sexe22', 'Nom22', 'Prénom22', 'Nuance22', 'Voix22', '% Voix/Ins22', '% Voix/Exp22']

In [34]:
raw_2022_leg_T2["Election"] = "Legislatives 2022"
raw_2022_leg_T2["Tour"] = 2

## `Législatives 2017`

### **Tour 1**

In [35]:
file = 'data/Leg_2017_Resultats_BVT_T1_c.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)),skiprows=1)

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1107141887.py:2: DtypeWarning: Columns (0,6,150,151,152,153,155,156,158,159,160,161,163,164,166,167,168,169,171,172,174,175,176,177,179,180,182,183,184,185,187,188,190,191,192,193,195,196,198,199,200,201,203,204,206,207,208,209,211,212,214,215,216,217,219,220,222,223,224,225,227,228,230,231,232,233,235,236) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)),skiprows=1)

In [36]:
df

,0,1,2,3,4,5,6,7,8,9,...,227,228,229,230,231,232,233,234,235,236
0,1,Ain,4,4ème circonscription,1,L'Abergement-Clémenciat,1,598,261,"43,65",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Ain,5,5ème circonscription,2,L'Abergement-de-Varey,1,211,79,"37,44",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,1,1126,637,"56,57",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,2,1134,579,"51,06",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Ain,5,5ème circonscription,4,Ambérieu-en-Bugey,3,1117,560,"50,13",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69237,ZZ,Français établis hors de France,10,10ème circonscription,227,Yaounde,1,1518,1166,"76,81",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69238,ZZ,Français établis hors de France,7,7ème circonscription,228,Zagreb,1,656,528,"80,49",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69239,ZZ,Français établis hors de France,6,6ème circonscription,229,Zurich,1,21502,16821,"78,23",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69240,ZZ,Français établis hors de France,11,11ème circonscription,231,Taipeh,1,1212,903,"74,50",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
69241,ZZ,Français établis hors de France,2,2ème circonscription,232,Nassau,1,116,102,"87,93",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
#df = df.drop([0], axis=0)
df=extract_data(df, df.shape[1])
raw_2017_leg_T1 = df

['N°Panneau1', 'Sexe1', 'Nom1', 'Prénom1', 'Nuance1', 'Voix1', '% Voix/Ins1', '% Voix/Exp1']
['N°Panneau2', 'Sexe2', 'Nom2', 'Prénom2', 'Nuance2', 'Voix2', '% Voix/Ins2', '% Voix/Exp2']
['N°Panneau3', 'Sexe3', 'Nom3', 'Prénom3', 'Nuance3', 'Voix3', '% Voix/Ins3', '% Voix/Exp3']
['N°Panneau4', 'Sexe4', 'Nom4', 'Prénom4', 'Nuance4', 'Voix4', '% Voix/Ins4', '% Voix/Exp4']
['N°Panneau5', 'Sexe5', 'Nom5', 'Prénom5', 'Nuance5', 'Voix5', '% Voix/Ins5', '% Voix/Exp5']
['N°Panneau6', 'Sexe6', 'Nom6', 'Prénom6', 'Nuance6', 'Voix6', '% Voix/Ins6', '% Voix/Exp6']
['N°Panneau7', 'Sexe7', 'Nom7', 'Prénom7', 'Nuance7', 'Voix7', '% Voix/Ins7', '% Voix/Exp7']
['N°Panneau8', 'Sexe8', 'Nom8', 'Prénom8', 'Nuance8', 'Voix8', '% Voix/Ins8', '% Voix/Exp8']
['N°Panneau9', 'Sexe9', 'Nom9', 'Prénom9', 'Nuance9', 'Voix9', '% Voix/Ins9', '% Voix/Exp9']
['N°Panneau10', 'Sexe10', 'Nom10', 'Prénom10', 'Nuance10', 'Voix10', '% Voix/Ins10', '% Voix/Exp10']
['N°Panneau11', 'Sexe11', 'Nom11', 'Prénom11', 'Nuance11', 'Voix11', '% Voix/Ins11', '% Voix/Exp11']
['N°Panneau12', 'Sexe12', 'Nom12', 'Prénom12', 'Nuance12', 'Voix12', '% Voix/Ins12', '% Voix/Exp12']
['N°Panneau13', 'Sexe13', 'Nom13', 'Prénom13', 'Nuance13', 'Voix13', '% Voix/Ins13', '% Voix/Exp13']
['N°Panneau14', 'Sexe14', 'Nom14', 'Prénom14', 'Nuance14', 'Voix14', '% Voix/Ins14', '% Voix/Exp14']
['N°Panneau15', 'Sexe15', 'Nom15', 'Prénom15', 'Nuance15', 'Voix15', '% Voix/Ins15', '% Voix/Exp15']
['N°Panneau16', 'Sexe16', 'Nom16', 'Prénom16', 'Nuance16', 'Voix16', '% Voix/Ins16', '% Voix/Exp16']
['N°Panneau17', 'Sexe17', 'Nom17', 'Prénom17', 'Nuance17', 'Voix17', '% Voix/Ins17', '% Voix/Exp17']
['N°Panneau18', 'Sexe18', 'Nom18', 'Prénom18', 'Nuance18', 'Voix18', '% Voix/Ins18', '% Voix/Exp18']
['N°Panneau19', 'Sexe19', 'Nom19', 'Prénom19', 'Nuance19', 'Voix19', '% Voix/Ins19', '% Voix/Exp19']
['N°Panneau20', 'Sexe20', 'Nom20', 'Prénom20', 'Nuance20', 'Voix20', '% Voix/Ins20', '% Voix/Exp20']
['N°Panneau21', 'Sexe21', 'Nom21', 'Prénom21', 'Nuance21', 'Voix21', '% Voix/Ins21', '% Voix/Exp21']
['N°Panneau22', 'Sexe22', 'Nom22', 'Prénom22', 'Nuance22', 'Voix22', '% Voix/Ins22', '% Voix/Exp22']
['N°Panneau23', 'Sexe23', 'Nom23', 'Prénom23', 'Nuance23', 'Voix23', '% Voix/Ins23', '% Voix/Exp23']
['N°Panneau24', 'Sexe24', 'Nom24', 'Prénom24', 'Nuance24', 'Voix24', '% Voix/Ins24', '% Voix/Exp24']
['N°Panneau25', 'Sexe25', 'Nom25', 'Prénom25', 'Nuance25', 'Voix25', '% Voix/Ins25', '% Voix/Exp25']
['N°Panneau26', 'Sexe26', 'Nom26', 'Prénom26', 'Nuance26', 'Voix26', '% Voix/Ins26', '% Voix/Exp26']
['N°Panneau27', 'Sexe27', 'Nom27', 'Prénom27', 'Nuance27', 'Voix27', '% Voix/Ins27', '% Voix/Exp27']

In [38]:
raw_2017_leg_T1["Election"] = "Legislatives 2017"
raw_2017_leg_T1["Tour"] = 1

### **Tour 2**

In [39]:
file = 'data/Leg_2017_Resultats_BVT_T2_c.csv'
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))
df = df.drop([0], axis=0)
df=extract_data(df, df.shape[1])
raw_2017_leg_T2 = df

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/467176188.py:2: DtypeWarning: Columns (0,2,4,6,7,8,10,12,15,18,21,26,38,39,40,41,43,44) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))

['N°Panneau1', 'Sexe1', 'Nom1', 'Prénom1', 'Nuance1', 'Voix1', '% Voix/Ins1', '% Voix/Exp1']
['N°Panneau2', 'Sexe2', 'Nom2', 'Prénom2', 'Nuance2', 'Voix2', '% Voix/Ins2', '% Voix/Exp2']
['N°Panneau3', 'Sexe3', 'Nom3', 'Prénom3', 'Nuance3', 'Voix3', '% Voix/Ins3', '% Voix/Exp3']
['N°Panneau4', 'Sexe4', 'Nom4', 'Prénom4', 'Nuance4', 'Voix4', '% Voix/Ins4', '% Voix/Exp4']
['N°Panneau5', 'Sexe5', 'Nom5', 'Prénom5', 'Nuance5', 'Voix5', '% Voix/Ins5', '% Voix/Exp5']
['N°Panneau6', 'Sexe6', 'Nom6', 'Prénom6', 'Nuance6', 'Voix6', '% Voix/Ins6', '% Voix/Exp6']
['N°Panneau7', 'Sexe7', 'Nom7', 'Prénom7', 'Nuance7', 'Voix7', '% Voix/Ins7', '% Voix/Exp7']
['N°Panneau8', 'Sexe8', 'Nom8', 'Prénom8', 'Nuance8', 'Voix8', '% Voix/Ins8', '% Voix/Exp8']
['N°Panneau9', 'Sexe9', 'Nom9', 'Prénom9', 'Nuance9', 'Voix9', '% Voix/Ins9', '% Voix/Exp9']
['N°Panneau10', 'Sexe10', 'Nom10', 'Prénom10', 'Nuance10', 'Voix10', '% Voix/Ins10', '% Voix/Exp10']
['N°Panneau11', 'Sexe11', 'Nom11', 'Prénom11', 'Nuance11', 'Voix11', '% Voix/Ins11', '% Voix/Exp11']
['N°Panneau12', 'Sexe12', 'Nom12', 'Prénom12', 'Nuance12', 'Voix12', '% Voix/Ins12', '% Voix/Exp12']
['N°Panneau13', 'Sexe13', 'Nom13', 'Prénom13', 'Nuance13', 'Voix13', '% Voix/Ins13', '% Voix/Exp13']
['N°Panneau14', 'Sexe14', 'Nom14', 'Prénom14', 'Nuance14', 'Voix14', '% Voix/Ins14', '% Voix/Exp14']
['N°Panneau15', 'Sexe15', 'Nom15', 'Prénom15', 'Nuance15', 'Voix15', '% Voix/Ins15', '% Voix/Exp15']
['N°Panneau16', 'Sexe16', 'Nom16', 'Prénom16', 'Nuance16', 'Voix16', '% Voix/Ins16', '% Voix/Exp16']
['N°Panneau17', 'Sexe17', 'Nom17', 'Prénom17', 'Nuance17', 'Voix17', '% Voix/Ins17', '% Voix/Exp17']
['N°Panneau18', 'Sexe18', 'Nom18', 'Prénom18', 'Nuance18', 'Voix18', '% Voix/Ins18', '% Voix/Exp18']
['N°Panneau19', 'Sexe19', 'Nom19', 'Prénom19', 'Nuance19', 'Voix19', '% Voix/Ins19', '% Voix/Exp19']
['N°Panneau20', 'Sexe20', 'Nom20', 'Prénom20', 'Nuance20', 'Voix20', '% Voix/Ins20', '% Voix/Exp20']
['N°Panneau21', 'Sexe21', 'Nom21', 'Prénom21', 'Nuance21', 'Voix21', '% Voix/Ins21', '% Voix/Exp21']
['N°Panneau22', 'Sexe22', 'Nom22', 'Prénom22', 'Nuance22', 'Voix22', '% Voix/Ins22', '% Voix/Exp22']
['N°Panneau23', 'Sexe23', 'Nom23', 'Prénom23', 'Nuance23', 'Voix23', '% Voix/Ins23', '% Voix/Exp23']
['N°Panneau24', 'Sexe24', 'Nom24', 'Prénom24', 'Nuance24', 'Voix24', '% Voix/Ins24', '% Voix/Exp24']
['N°Panneau25', 'Sexe25', 'Nom25', 'Prénom25', 'Nuance25', 'Voix25', '% Voix/Ins25', '% Voix/Exp25']
['N°Panneau26', 'Sexe26', 'Nom26', 'Prénom26', 'Nuance26', 'Voix26', '% Voix/Ins26', '% Voix/Exp26']
['N°Panneau27', 'Sexe27', 'Nom27', 'Prénom27', 'Nuance27', 'Voix27', '% Voix/Ins27', '% Voix/Exp27']

In [40]:
raw_2017_leg_T2["Election"] = "Legislatives 2017"
raw_2017_leg_T2["Tour"] = 2

## `Législatives : 2012`

### **Tour 1 et 2**

In [41]:
file = "data/LG12_Bvot_T1T2.csv"
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/1860040836.py:2: DtypeWarning: Columns (0,1,6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))

In [42]:
df

,0,1,2,3,4,5,6,7,8,9,...,227,228,229,230,231,232,233,234,235,236
0,-- Résultats par bureau de vote Législatives ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-- ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-- Champ 1 : N° tour ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-- Champ 2 : Code département ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-- Champ 3 : Code de la commune ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
868483,2,95,680.0,Villiers-le-Bel,8.0,35.0,13,658.0,240.0,229.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868484,2,95,682.0,Villiers-le-Sec,9.0,15.0,1,95.0,71.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868485,2,95,682.0,Villiers-le-Sec,9.0,15.0,1,95.0,71.0,71.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868486,2,95,690.0,Wy-dit-Joli-Village,1.0,16.0,1,277.0,181.0,178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
868487,2,95,690.0,Wy-dit-Joli-Village,1.0,16.0,1,277.0,181.0,178.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
Colonnes = ['Tour',
'Code du département',
'Code de la commune',
'Libellé de la commune',
'Code de la circonscription',
'Code du canton',
'Code du b.vote',
'Inscrits',
'Votants',
'Exprimés',
'N°Panneau',
'Nom',
'Prénom',
'Nuance',
'Voix']

In [44]:
#drop 18 first rows 
df = df.drop(list(range(18)), axis=0)
df.dropna(axis=1, how='all', inplace=True)
df.columns = Colonnes

In [45]:
raw_2012_leg_T1T2 = df
raw_2012_leg_T1T2["Election"] = "Legislatives 2012"

## `Législatives : 2007`

### **Tour 1 et 2**

In [46]:
file = "data/LG07_Bvot_T1T2.csv"
df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))

/var/folders/rc/0g2xxgc57fq40kc5jwsm7h_c0000gn/T/ipykernel_40020/3209020231.py:2: DtypeWarning: Columns (0,1,4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file, sep=";", encoding="latin-1", names = list(range(237)))

In [47]:
df

,0,1,2,3,4,5,6,7,8,9,...,227,228,229,230,231,232,233,234,235,236
0,-- Résultats par bureau de vote Législatives ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,-- ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,-- ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,-- Champ 1 : N° tour ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,-- Champ 2 : Code département ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965301,2,ZM,517.0,TSINGONI,73,695.0,345.0,337.0,10.0,KAMARDINE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965302,2,ZM,517.0,TSINGONI,74,635.0,249.0,235.0,9.0,ALY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965303,2,ZM,517.0,TSINGONI,74,635.0,249.0,235.0,10.0,KAMARDINE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965304,2,ZM,517.0,TSINGONI,99,174.0,86.0,82.0,9.0,ALY,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
965305,2,ZM,517.0,TSINGONI,99,174.0,86.0,82.0,10.0,KAMARDINE,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [48]:
Colonnes = ['Tour',
'Code du département',
'Code de la commune',
'Libellé de la commune',
'Code du b.vote',
'Inscrits',
'Votants',
'Exprimés',
'N°Panneau',
'Nom',
'Prénom',
'Nuance',
'Voix']

df = df.drop(list(range(18)), axis=0)
df.dropna(axis=1, how='all', inplace=True)
df.columns = Colonnes

In [49]:
raw_2007_leg_T1T2 = df

raw_2007_leg_T1T2["Election"] = "Legislatives 2007"

***
***

Nous disposons à ce niveau des datasets suivants : 

- `Présidentielles 2022` :
    - raw_2022_T1
    - raw_2022_T2
- `Législatives 2022` :
    - raw_2022_leg_T1
    - raw_2022_leg_T2

- `Présidentielles 2017` :
    - raw_T1_2017
    - raw_T2_2017
- `Législatives 2017` :
    - raw_2017_leg_T1
    - raw_2017_leg_T2

- `Présidentielles 2012` :
    - raw_2012_T1T2
- `Législatives 2012` :
    - raw_2012_leg_T1T2

- `Présidentielles 2007` :
    - raw_2007_T1T2
- `Législatives 2097` :
    - raw_2007_leg_T1T2

In [50]:
def concatenation(df1,df2) : 
    print("df1 shape is ", df1.shape)
    print("")
    print("df2 shape is ", df2.shape)

    df = pd.concat([df1,df2], axis = 0)

    print("df shape is ", df.shape)
    print("good concat on rows: ", df.shape[0] == df1.shape[0] + df2.shape[0])
    print("good concat on columns: ", (df.shape[1] == df1.shape[1],  df.shape[1] == df2.shape[1]))

    return df

In [51]:
pres_2022_T1T2 = concatenation(raw_2022_T1,raw_2022_T2)

df1 shape is  (836184, 28)

df2 shape is  (139364, 28)
df shape is  (975548, 28)
good concat on rows:  True
good concat on columns:  (True, True)

In [52]:
leg_2022_T1T2 = concatenation(raw_2022_leg_T1, raw_2022_leg_T2 )

df1 shape is  (1533026, 29)

df2 shape is  (1533026, 29)
df shape is  (3066052, 29)
good concat on rows:  True
good concat on columns:  (True, True)

In [53]:
pres_2017_T1T2 = concatenation(raw_T1_2017,raw_T2_2017)

df1 shape is  (761662, 28)

df2 shape is  (138484, 28)
df shape is  (900146, 28)
good concat on rows:  True
good concat on columns:  (True, True)

In [54]:
leg_2017_T1T2 = concatenation(raw_2017_leg_T1, raw_2017_leg_T2 )

df1 shape is  (1869534, 29)

df2 shape is  (1856736, 29)
df shape is  (3726270, 29)
good concat on rows:  True
good concat on columns:  (True, True)

Nous disposons à ce niveau des datasets suivants : 

- `Présidentielles 2022` :
    - pres_2022_T1T2
- `Législatives 2022` :
    - leg_2022_T1T1
- `Présidentielles 2017` :
    - pres_2017_T1T2
- `Législatives 2017` :
    - leg_2017_T1T1
- `Présidentielles 2012` :
    - raw_2012_T1T2
- `Législatives 2012` :
    - raw_2012_leg_T1T2

- `Présidentielles 2007` :
    - raw_2007_T1T2
- `Législatives 2097` :
    - raw_2007_leg_T1T2

In [55]:
#function that takes several dataframe and gives the common columns
from functools import reduce 

def common_columns(*args):
    common = set(args[0].columns)
    for i in range(1, len(args)):
        common = common.intersection(set(args[i].columns))
    return list(common)

common_columns(raw_2022_leg_T1, raw_2022_leg_T2, raw_2017_leg_T1, raw_2017_leg_T2, raw_2012_leg_T1T2, raw_2007_leg_T1T2)


result = list(reduce(set.intersection, map(set,[raw_2022_leg_T1.columns, 
                                                raw_2022_leg_T2.columns, 
                                                raw_2017_leg_T1.columns, 
                                                raw_2017_leg_T2.columns, 
                                                raw_2012_leg_T1T2.columns, 
                                                raw_2007_leg_T1T2.columns])))

In [56]:
result

['Code du département',
 'Tour',
 'Prénom',
 'Code de la commune',
 'Exprimés',
 'Inscrits',
 'Nom',
 'Nuance',
 'Voix',
 'Code du b.vote',
 'Libellé de la commune',
 'Election',
 'Votants']

In [57]:
dfs = [pres_2022_T1T2,leg_2022_T1T2,pres_2017_T1T2,leg_2017_T1T2,raw_2012_leg_T1T2,raw_2007_leg_T1T2]

df = pd.DataFrame(columns= result)
for ele in dfs : 
    df = pd.concat([df,ele], axis = 0)

df=df[["Election", "Tour","Code du département","Code de la commune","Libellé de la commune", "Code du b.vote", "Inscrits", "Votants", "Exprimés", "Nom", "Prénom", "Nuance", "Voix"]]

***
***

In [58]:
all_results = df

In [59]:
all_results

,Election,Tour,Code du département,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Votants,Exprimés,Nom,Prénom,Nuance,Voix
0,Presidentielle 2022,1,01,1,L'Abergement-Clémenciat,0001,645,537,520,ARTHAUD,Nathalie,NaN,3
1,Presidentielle 2022,1,01,2,L'Abergement-de-Varey,0001,213,175,171,ARTHAUD,Nathalie,NaN,2
2,Presidentielle 2022,1,01,4,Ambérieu-en-Bugey,0001,1129,863,840,ARTHAUD,Nathalie,NaN,4
3,Presidentielle 2022,1,01,4,Ambérieu-en-Bugey,0002,1128,863,842,ARTHAUD,Nathalie,NaN,6
4,Presidentielle 2022,1,01,4,Ambérieu-en-Bugey,0003,1213,967,949,ARTHAUD,Nathalie,NaN,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
965301,Legislatives 2007,2,ZM,517.0,TSINGONI,73,695.0,345.0,337.0,KAMARDINE,Mansour,UMP,181.0
965302,Legislatives 2007,2,ZM,517.0,TSINGONI,74,635.0,249.0,235.0,ALY,Abdoulatifou,DIV,128.0
965303,Legislatives 2007,2,ZM,517.0,TSINGONI,74,635.0,249.0,235.0,KAMARDINE,Mansour,UMP,107.0
965304,Legislatives 2007,2,ZM,517.0,TSINGONI,99,174.0,86.0,82.0,ALY,Abdoulatifou,DIV,29.0
965305,Legislatives 2007,2,ZM,517.0,TSINGONI,99,174.0,86.0,82.0,KAMARDINE,Mansour,UMP,53.0

In [60]:
all_results["Code de la commune"].fillna(0, inplace=True)
all_results["Code de la commune"].replace("nan", 0, inplace=True)
all_results["Code de la commune"] = all_results["Code de la commune"].apply(lambda  x : str(int(x)).zfill(3))

all_results["Code du département"] = all_results["Code du département"].apply(lambda  x : str(x).zfill(2))

all_results["Code INSEE"]=all_results["Code du département"]+ all_results["Code de la commune"]

In [61]:
all_results['Code du b.vote'] = all_results['Code du b.vote'].apply(lambda x: str(x).zfill(5))

In [73]:
all_results

,Election,Tour,Code du département,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Votants,Exprimés,Nom,Prénom,Nuance,Voix,Code INSEE
0,Presidentielle 2022,1,01,001,L'Abergement-Clémenciat,00001,645,537,520,ARTHAUD,Nathalie,NaN,3,01001
1,Presidentielle 2022,1,01,002,L'Abergement-de-Varey,00001,213,175,171,ARTHAUD,Nathalie,NaN,2,01002
2,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00001,1129,863,840,ARTHAUD,Nathalie,NaN,4,01004
3,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00002,1128,863,842,ARTHAUD,Nathalie,NaN,6,01004
4,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00003,1213,967,949,ARTHAUD,Nathalie,NaN,8,01004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965301,Legislatives 2007,2,ZM,517,TSINGONI,00073,695.0,345.0,337.0,KAMARDINE,Mansour,UMP,181.0,ZM517
965302,Legislatives 2007,2,ZM,517,TSINGONI,00074,635.0,249.0,235.0,ALY,Abdoulatifou,DIV,128.0,ZM517
965303,Legislatives 2007,2,ZM,517,TSINGONI,00074,635.0,249.0,235.0,KAMARDINE,Mansour,UMP,107.0,ZM517
965304,Legislatives 2007,2,ZM,517,TSINGONI,00099,174.0,86.0,82.0,ALY,Abdoulatifou,DIV,29.0,ZM517
965305,Legislatives 2007,2,ZM,517,TSINGONI,00099,174.0,86.0,82.0,KAMARDINE,Mansour,UMP,53.0,ZM517

### Bureaux de vote

In [63]:
file = "data/bureaux-vote-france-2017.csv"
df = pd.read_csv(file, sep=";", encoding="utf-8")

In [64]:
df['Code INSEE'].fillna(0, inplace=True)

In [65]:
df['Code INSEE'].value_counts().sort_values(ascending=False)

0.0        539
31555.0    263
6088.0     251
44109.0    200
67482.0    143
          ...
24010.0      1
24009.0      1
19168.0      1
19125.0      1
26138.0      1
Name: Code INSEE, Length: 33384, dtype: int64

In [66]:
all_results

,Election,Tour,Code du département,Code de la commune,Libellé de la commune,Code du b.vote,Inscrits,Votants,Exprimés,Nom,Prénom,Nuance,Voix,Code INSEE
0,Presidentielle 2022,1,01,001,L'Abergement-Clémenciat,00001,645,537,520,ARTHAUD,Nathalie,NaN,3,01001
1,Presidentielle 2022,1,01,002,L'Abergement-de-Varey,00001,213,175,171,ARTHAUD,Nathalie,NaN,2,01002
2,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00001,1129,863,840,ARTHAUD,Nathalie,NaN,4,01004
3,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00002,1128,863,842,ARTHAUD,Nathalie,NaN,6,01004
4,Presidentielle 2022,1,01,004,Ambérieu-en-Bugey,00003,1213,967,949,ARTHAUD,Nathalie,NaN,8,01004
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965301,Legislatives 2007,2,ZM,517,TSINGONI,00073,695.0,345.0,337.0,KAMARDINE,Mansour,UMP,181.0,ZM517
965302,Legislatives 2007,2,ZM,517,TSINGONI,00074,635.0,249.0,235.0,ALY,Abdoulatifou,DIV,128.0,ZM517
965303,Legislatives 2007,2,ZM,517,TSINGONI,00074,635.0,249.0,235.0,KAMARDINE,Mansour,UMP,107.0,ZM517
965304,Legislatives 2007,2,ZM,517,TSINGONI,00099,174.0,86.0,82.0,ALY,Abdoulatifou,DIV,29.0,ZM517
965305,Legislatives 2007,2,ZM,517,TSINGONI,00099,174.0,86.0,82.0,KAMARDINE,Mansour,UMP,53.0,ZM517

In [67]:
df

,Bureau de vote,Code INSEE,Code Bureau Vote,Heure d'ouverture,Heure de fermeture,Code Postal,Ville,Nom Bureau Vote,Adresse,Adresse Substitution,Coordonnées,Département,uniq_bdv
0,Bureau de vote unique,16388.0,0001,8,19,16730.0,Trois-Palis,Mairie,NaN,Mairie,"45.639328, 0.054523",16,Mairie - Trois-Palis
1,Bureau de vote unique,2472.0,0001,8,19,2820.0,Mauregny-en-Haye,Ecole,Rue Jean Moulin,Rue Jean Moulin,"49.532043, 3.799944",02,Ecole - Mauregny-en-Haye
2,Bureau de vote n°1,2439.0,0001,8,19,2160.0,Les Septvallons,Territoire de Glennes,"8, rue de la Lombardie","8, rue de la Lombardie","49.356748, 3.710401",02,Territoire de Glennes - Les Septvallons
3,Bureau de vote unique,11338.0,0001,8,19,11300.0,Saint-Couat-du-Razès,Mairie,Le village,Le village,"43.000056, 2.1092",11,Mairie - Saint-Couat-du-Razès
4,Bureau de vote unique,11307.0,0001,8,19,11200.0,Raissac-d'Aude,Mairie,2 rue de la république,2 rue de la république,"43.228158, 2.879355",11,Mairie - Raissac-d'Aude
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65482,Bureau de vote n°16,0.0,NaN,8,19,20200.0,Bastia,Groupe Scolaire Joseph Calloni - école Materne...,NaN,Groupe Scolaire Joseph Calloni - école Materne...,"42.722711, 9.454682",No,Groupe Scolaire Joseph Calloni - école Materne...
65483,Bureau de vote unique,21138.0,0001,8,19,21130.0,Champdôtre,Mairie,42 grande rue,42 grande rue,"47.181437, 5.303905",21,Mairie - Champdôtre
65484,Bureau de vote unique,26352.0,0001,8,19,26160.0,La Touche,Salle de la Cantine mitoyenne à la Mairie,Le Village,Le Village,"44.51435, 4.887578",26,Salle de la Cantine mitoyenne à la Mairie - L...
65485,Bureau de vote unique,26154.0,0001,8,19,26560.0,Lachau,Salle de la mairie,Place de la mairie,Place de la mairie,"44.231414, 5.638027",26,Salle de la mairie - Lachau
65486,Bureau de vote unique,26138.0,0001,8,19,26700.0,La Garde-Adhémar,Mairie - salle des mariages,Rue Pauline de Simiane,Rue Pauline de Simiane,"44.392989, 4.752669",26,Mairie - salle des mariages - La Garde-Adhémar

In [68]:
df["Code INSEE"]=df["Code INSEE"].apply(lambda  x : str(int(x)).zfill(5))
df

,Bureau de vote,Code INSEE,Code Bureau Vote,Heure d'ouverture,Heure de fermeture,Code Postal,Ville,Nom Bureau Vote,Adresse,Adresse Substitution,Coordonnées,Département,uniq_bdv
0,Bureau de vote unique,16388,0001,8,19,16730.0,Trois-Palis,Mairie,NaN,Mairie,"45.639328, 0.054523",16,Mairie - Trois-Palis
1,Bureau de vote unique,02472,0001,8,19,2820.0,Mauregny-en-Haye,Ecole,Rue Jean Moulin,Rue Jean Moulin,"49.532043, 3.799944",02,Ecole - Mauregny-en-Haye
2,Bureau de vote n°1,02439,0001,8,19,2160.0,Les Septvallons,Territoire de Glennes,"8, rue de la Lombardie","8, rue de la Lombardie","49.356748, 3.710401",02,Territoire de Glennes - Les Septvallons
3,Bureau de vote unique,11338,0001,8,19,11300.0,Saint-Couat-du-Razès,Mairie,Le village,Le village,"43.000056, 2.1092",11,Mairie - Saint-Couat-du-Razès
4,Bureau de vote unique,11307,0001,8,19,11200.0,Raissac-d'Aude,Mairie,2 rue de la république,2 rue de la république,"43.228158, 2.879355",11,Mairie - Raissac-d'Aude
...,...,...,...,...,...,...,...,...,...,...,...,...,...
65482,Bureau de vote n°16,00000,NaN,8,19,20200.0,Bastia,Groupe Scolaire Joseph Calloni - école Materne...,NaN,Groupe Scolaire Joseph Calloni - école Materne...,"42.722711, 9.454682",No,Groupe Scolaire Joseph Calloni - école Materne...
65483,Bureau de vote unique,21138,0001,8,19,21130.0,Champdôtre,Mairie,42 grande rue,42 grande rue,"47.181437, 5.303905",21,Mairie - Champdôtre
65484,Bureau de vote unique,26352,0001,8,19,26160.0,La Touche,Salle de la Cantine mitoyenne à la Mairie,Le Village,Le Village,"44.51435, 4.887578",26,Salle de la Cantine mitoyenne à la Mairie - L...
65485,Bureau de vote unique,26154,0001,8,19,26560.0,Lachau,Salle de la mairie,Place de la mairie,Place de la mairie,"44.231414, 5.638027",26,Salle de la mairie - Lachau
65486,Bureau de vote unique,26138,0001,8,19,26700.0,La Garde-Adhémar,Mairie - salle des mariages,Rue Pauline de Simiane,Rue Pauline de Simiane,"44.392989, 4.752669",26,Mairie - salle des mariages - La Garde-Adhémar

In [69]:
#df1 = pd.merge(df, all_results, how='right', left_on=['Code INSEE',], right_on = ['Code INSEE'])

In [70]:
# print(df1.shape)
# df1.head()

In [71]:

# del df

In [72]:
#df1.to_csv('data/datagabouquejaimesuperfortsuperfortplusfortquetoutaumondeplusfortquefortPLUSFORTQUELAVIE-QUELAMORT-QUELENNUI-QUELAMOUR-QUELESOUFFLEQUIBATQUEJINSPIREETQUIUNJOUREXPIRERASUREMENTAUDETOURDUNREGARDECHANGEAVECCELLEQUONNEVEUTJAMAISVOIR.csv', sep=';')